framework:
    asset_mapper:
        # The paths to make available to the asset mapper.
        paths:
            - assets/
            - { value: '%kernel.project_dir%/vendor/symfony/ux-turbo/assets/dist', namespace: '@symfony/ux-turbo' }
        missing_import_mode: strict

when@prod:
    framework:
        asset_mapper:
            missing_import_mode: warn
